<a href="https://colab.research.google.com/github/amberlylanger/Projects-for-Linear-Algebra/blob/master/Practice_with_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [4]:
# examples of matrix and vector definition

# create the matrix:
M = np.matrix([[1, -1, 0, 0],
               [1, 0, -1, 0],
               [0, 1, -1, 0],
               [0, 0, -1, 1],
               [-1, 0, 0, 1]])


# create the vector for the right hand side:
pts = np.matrix([[1], [14], [38], [11], [20]])
 
#Make sure the system looks appropriate:
print(np.c_[M,pts])

[[ 1 -1  0  0  1]
 [ 1  0 -1  0 14]
 [ 0  1 -1  0 38]
 [ 0  0 -1  1 11]
 [-1  0  0  1 20]]


In [5]:
pts

matrix([[ 1],
        [14],
        [38],
        [11],
        [20]])

In [6]:
# how do I do a dot product?
np.dot([1,4],[3,6])

27

In [7]:
# How do I find the magnitude in np?
np.sqrt(np.dot([1,4],[3,6]))

5.196152422706632

In [8]:
# Define the original vectors:

r1= [2,4,0,0]
r2= [1,2,3,6]
r3= [2,-1,2,-1]
r4= [1,2,3,4]

# look at r1:
r1

[2, 4, 0, 0]

In [11]:
# find the first nice basis vector u1:

# 1: Pick a new vector
r1

# 2:subtract the projection of r1 onto the nice basis u1, u2, u3...
# and save this as a temp vector n1

n1=r1
r1

#3: find the magnitude of n1
np.sqrt(np.dot(n1,n1))

#4: create a nice basis vector u1=1/ |n1| * n1
u1= n1/ np.sqrt(np.dot(n1,n1))
u1

array([0.4472136 , 0.89442719, 0.        , 0.        ])

In [12]:
# check that u1 has magnitude 1:
np.dot(u1,u1)

0.9999999999999999

In [14]:
# find the second nice basis vector u2:

# 1: Pick a new vector
r2

# 2:subtract the projection of r2 onto the nice basis u1, u2, u3...
# and save this as a temp vector n2

n2=r2- np.dot(r2, u1)*u1
r2

#3: find the magnitude of n2
np.sqrt(np.dot(n2,n2))

#4: create a nice basis vector u2=1/ |n2| * n2
u2= n2/ np.sqrt(np.dot(n2,n2))
u2

array([0.        , 0.        , 0.4472136 , 0.89442719])

In [15]:
# check that u1 and u2 are othongoal:
np.dot(u1,u2)
#check that u2 has magnitude of 1:
np.dot(u2,u2)

0.9999999999999999

In [18]:
# find the second nice basis vector u3:

# 1: Pick a new vector
r3

# 2:subtract the projection of r3 onto the nice basis u1, u2, u3...
# and save this as a temp vector n3

n3=r3- np.dot(r3, u1)*u1 - np.dot(r3, u2)* u2
r3

#3: find the magnitude of n3
np.sqrt(np.dot(n3,n3))

#4: create a nice basis vector u3=1/ |n3| * n3
u3= n3/ np.sqrt(np.dot(n3,n3))
u3

array([ 0.63245553, -0.31622777,  0.63245553, -0.31622777])

In [19]:
# check that u3 is orthogonal to u1 and u2:
np.dot(u1,u3)
#check that u2 has magnitude of 1:
np.dot(u3,u3)

1.0

In [20]:
# find the second nice basis vector u4:

# 1: Pick a new vector
r4

# 2:subtract the projection of r4 onto the nice basis u1, u2, u3...
# and save this as a temp vector n4

n4=r4- np.dot(r4, u1)*u1 - np.dot(r4, u2)* u2 - np.dot(r4,u3)*u3
r4

#3: find the magnitude of n4
np.sqrt(np.dot(n4,n4))

#4: create a nice basis vector u4=1/ |n4| * n4
u4= n4/ np.sqrt(np.dot(n4,n4))
u4

array([-0.63245553,  0.31622777,  0.63245553, -0.31622777])

In [23]:
# check that u4 is orthogonal to u1 and u2 and u3:
print(np.dot(u4,u1))
print(np.dot(u4,u2))
print(np.dot(u4,u3))
#check that u4 has magnitude of 1:
print(np.dot(u4,u4))

0.0
9.43689570931383e-16
9.71445146547012e-17
0.9999999999999998
